language: php

php:
  - 5.6
  - 7.2
  - 7.3

env: 
  - SYMFONY_VERSION=^2.8
  - SYMFONY_VERSION=^3.4
  - SYMFONY_VERSION=^4.2

matrix:
  exclude:
    php: 5.6
    env: SYMFONY_VERSION=^4.2


cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer require symfony/symfony:${SYMFONY_VERSION}

script:
    - ./vendor/bin/phpunit
