language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env: 
  - SYMFONY_VERSION=2.3.* 
  - SYMFONY_VERSION=2.4.* 
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.0.*

matrix:
  exclude:
  - php: 5.3
    env: SYMFONY_VERSION=3.0.*
  - php: 5.4
    env: SYMFONY_VERSION=3.0.*

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer require symfony/symfony:${SYMFONY_VERSION}

script:
    - ./vendor/bin/phpunit
